name: morphomet
channels:
  - conda-forge
dependencies:
  - python=3.11

  # core numerical stack
  - numpy
  - scipy
  - pandas

  # geospatial stack
  - geopandas
  - shapely
  - rasterio
  - rasterstats
  - osmnx
  - libpysal
  - momepy
  - r-suncalc

  # visualization
  - jupyter
  - matplotlib
  - seaborn
  - plotly

  # stats / ML
  - statsmodels
  - scikit-learn

  # utilities
  - tqdm